CÂU 1

1. Cho đoạn code như hình bên dưới, các bạn khai báo sử dụng BatchNormalization của
pytorch với các tham số mặc định. Khi thực thi chương trình, kết quả in ra màn hình là?

In [2]:
pip install torch

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import torch
import torch.nn as nn
import numpy as np

data = np.array ([[[1, 6], [3, 4]]])
data = torch.tensor(data , dtype=torch.float32)

bnorm = nn.BatchNorm2d (1)
data = data.unsqueeze (0)
with torch.no_grad ():
    output = bnorm(data)
    print(output)

tensor([[[[-1.3867,  1.3867],
          [-0.2773,  0.2773]]]])


CÂU 2

Cho đoạn code như hình bên dưới, các bạn sử dụng phép toán concatenate (torch.cat) của
pytorch với axis=0, để concatenate 2 feature map lại với nhau. Khi thực thi chương trình,
kết quả in ra màn hình là?

In [6]:
import torch

a = torch.tensor ([[1, 2], [3, 4]])
b = torch.tensor ([[1, 2], [3, 4]])

a = a.reshape(1, 2, 2)
b = b.reshape(1, 2, 2)


c = torch.cat((a, b))
print(c)

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])


CÂU 4

Khi thực thi đoạn code sau đây, kết quả in ra màn hình là?

In [8]:
import torch
import torch.nn as nn

seed = 1
torch.manual_seed(seed)
input_tensor = torch.tensor ([[[[1.0 , 2.0], [3.0, 4.0]]]])

conv_layer = nn.Conv2d(in_channels =1, out_channels =1, kernel_size =2)
conv_output = conv_layer(input_tensor)

with torch.no_grad ():
    output = conv_output + input_tensor
    print(output)

tensor([[[[0.9935, 1.9935],
          [2.9935, 3.9935]]]])
